version: '3'
# https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docker-compose.yml
# mr-bolle
services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    cap_add:
       - NET_ADMIN
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    #hostname: ipsec-vpn-server
    container_name: ikev2-server
    networks:
      vpn-net2:
        ipv4_address: 172.25.1.4 

  pihole:
    image: pihole/pihole
    container_name: ikev2_pihole
    cap_add:
    - NET_ADMIN     
    dns:
    - 127.0.0.1
    - 1.1.1.1
    depends_on:
    - vpn
    ports:
    #- "553:53/tcp"
    #- "553:53/udp"
    - "8081:80/tcp"
    environment:
      WEBPASSWORD: fcvFjLIO2hWhkFCi
# #1 Digitalcourage | #2 Chaos Computer Club
      DNS1: 46.182.19.48
      DNS2: 213.73.91.35
    volumes:
    - ./pihole:/etc/pihole
    - ./pihole/dnsmasq.d:/etc/dnsmasq.d
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      vpn-net2:
        ipv4_address: 172.25.1.4     

# docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
networks:
  vpn-net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.1.0/24
          gateway: 172.25.1.1
#    external: true
